// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCjjTYfBgKgucUasB28lImVb0cFaGtx3Q',
    appId: '1:986741810915:web:18d242337ccb27a04087d6',
    messagingSenderId: '986741810915',
    projectId: 'app-dev-25186',
    authDomain: 'app-dev-25186.firebaseapp.com',
    storageBucket: 'app-dev-25186.firebasestorage.app',
    measurementId: 'G-1Z028RWKCL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgsyijFmRSwVgzuCrsIy5GkNX0Qpl0Tls',
    appId: '1:986741810915:android:d2c02c1657bd68ec4087d6',
    messagingSenderId: '986741810915',
    projectId: 'app-dev-25186',
    storageBucket: 'app-dev-25186.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHwIPdNM5qML3187CwIMa3398EPMW5a7o',
    appId: '1:986741810915:ios:3656ac39403abf8f4087d6',
    messagingSenderId: '986741810915',
    projectId: 'app-dev-25186',
    storageBucket: 'app-dev-25186.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHwIPdNM5qML3187CwIMa3398EPMW5a7o',
    appId: '1:986741810915:ios:3656ac39403abf8f4087d6',
    messagingSenderId: '986741810915',
    projectId: 'app-dev-25186',
    storageBucket: 'app-dev-25186.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCjjTYfBgKgucUasB28lImVb0cFaGtx3Q',
    appId: '1:986741810915:web:71ce634c8fe7282a4087d6',
    messagingSenderId: '986741810915',
    projectId: 'app-dev-25186',
    authDomain: 'app-dev-25186.firebaseapp.com',
    storageBucket: 'app-dev-25186.firebasestorage.app',
    measurementId: 'G-8LBY9E71B0',
  );
}
